version: '3.8'

services:
  app:
    image: imsyc075/express-app:latest
    container_name: node-app
    ports:
      - "3001:8080"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable="true"

  watchtower:
    image: containrrr/watchtower 
    environment:
      - WATCHTOWER_POLL_INTERVAL=60  # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped